# /config.yaml
environment:
  num_agents: 4
  max_steps: 100

agents:
  - id: 0
    name: Alice
    role: Researcher
    tools:
      - Internet access
      - Data analysis software
  - id: 1
    name: Bob
    role: Planner
    tools:
      - Project management software
      - Decision-making algorithms
  - id: 2
    name: Carol
    role: Executor
    tools:
      - Task automation tools
      - Progress tracking software
  - id: 3
    name: Dave
    role: Critic
    tools:
      - Evaluation frameworks
      - Feedback analysis tools

simulation:
  num_cycles: 10
